on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  x86_64:
    runs-on: ubuntu-20.04
    name: x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pip dependencies
        run: sudo pip install yamlish junit-xml
      - name: Build
        run: make -j$(nproc) -C tools/lkl
      - name: Tests
        run: mkdir /tmp/junit && make -C tools/lkl run-tests tests="--junit-dir /tmp/junit"
      - name: Save test results
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: /tmp/junit/*.xml
  checkpatch:
    runs-on: ubuntu-20.04
    name: checkpatch
    steps:
      - name: Checkout
        with:
          fetch-depth: 0
        uses: actions/checkout@v2
      - name: Install pip dependencies
        run: sudo pip install ply GitPython
      - name: Check coding style
        run: tools/lkl/scripts/checkpatch.sh
